export default {
  // 登录操作类型
  START_LOGIN: "START_LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  // 通知操作类型
  MARK_NOTIFICATION_AS_READ_BY_ID: "MARK_NOTIFICATION_AS_READ_BY_ID",
  MARK_ALL_NOTIFICATION_AS_READ: "MARK_ALL_NOTIFICATION_AS_READ",
  // TOGGLE_NOTIFICATION_LOADING: "TOGGLE_NOTIFICATION_LOADING"
  START_NOTIFICATION_POST: "START_NOTIFICATION_POST",
  FINISH_NOTIFICATION_POST: "FINISH_NOTIFICATION_POST",
  RECEIVED_NOTIFICATIONS: "RECEIVED_NOTIFICATIONS"
}